# conda env create -f environment.yml
name: uspas-ml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - ipywidgets
  - jupyterlab
  - pytorch
  - botorch
  - pygmo
  - matplotlib 
  - scipy
  - scikit-learn
  - pandas
  - seaborn
    # Documentation:
  - mkdocs
  - mkdocs-material
  - mkdocs-jupyter
  - pip
  - pip:
    - git+git://github.com/uspas/2021_optimization_and_ml
